name: Deploy image to Amazon ECR

on:
  push:
  pull_request_target:
    types: [opened, reopened, synchronize]
    # types: [submitted]
    branches:
      - 'develop'

env:
  AWS_REGION: ${{ vars.AWS_REGION }}         # set this to your preferred AWS region, e.g. us-west-1
  ECR_REPOSITORY: ${{ vars.ECR_REPOSITORY }} # set this to your Amazon ECR repository name
  PLATFORMS: ${{ vars.BUILD_PLATFORMS }}

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    environment: development
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Set short git commit SHA
        id: vars
        run: echo "sha_short=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT

      - name: Build and export
        uses: docker/build-push-action@v4
        env:
          VERSION: ${{ github.head_ref }}-${{ steps.vars.outputs.sha_short }}
        with:
          context: .
          build-args: APP_VERSION=${{ env.VERSION }}
          platforms: ${{ env.PLATFORMS }}
          tags: ${{ github.repository }}:latest
          outputs: type=docker,dest=/tmp/docker-image.tar

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: docker-image
          path: /tmp/docker-image.tar
  
  deploy_to_ecr:
    name: Deploy to Amazon ECR
    needs: build
    runs-on: ubuntu-latest
    environment: development

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Download artifact
        uses: actions/download-artifact@v3
        with:
          name: docker-image
          path: /tmp

      - name: Load image
        run: |
          docker load --input /tmp/docker-image.tar
          docker image ls -a

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          # role-to-assume: arn:aws:iam::123456789012:role/my-github-actions-role
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: Set short git commit SHA
        id: vars
        run: echo "sha_short=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT

      - name: Tag and push docker image to Amazon ECR
        id: push-image
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          GIT_HASH: $(git rev-parse --short ${{ github.sha }})
          IMAGE_TAG: ${{ github.head_ref }}-${{ steps.vars.outputs.sha_short }} 
        run: |
          docker tag ${{ github.repository }} $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG
          docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG
          echo "Docker image name in Amazon ECR: $ECR_REPOSITORY:$IMAGE_TAG" >> $GITHUB_STEP_SUMMARY
