name: "Assume AWS Role via OIDC"
on:
  workflow_call:
    inputs:
      role_arn:
        required: true
        type: string
      aws_region:
        required: false
        type: string
        default: eu-central-1

jobs:
  configure:
    runs-on: ubuntu-latest
    steps:
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: ${{ inputs.role_arn }}
          aws-region: ${{ inputs.aws_region }}
