name: Update Jira Fix Version

on:
  workflow_call:
    inputs:
      jira-server:
        description: 'Jira Server'
        required: true
        type: string
    secrets:
      JIRA_TOKEN:
        description: 'Jira Token'
        required: true

env:
  JIRA_SERVER: ${{ inputs.jira-server }}

jobs:
  sync-version-with-jira-issues:
    if: (startsWith(github.head_ref, 'rc/') || startsWith(github.head_ref, 'hotfix/')) && (github.base_ref == 'master' || github.base_ref == 'main')
    runs-on: ubuntu-latest
    steps:
      - name: Pull Request Checkout
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.ref }}
          fetch-depth: '0'
      - name: Install Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.11
      - name: Install dependencies
        run: pip install -r https://raw.githubusercontent.com/reportportal/jira-versions-sync/main/requirements.txt
      - name: Update Jira Issues
        run: python3 -c "$(wget -q -O - https://raw.githubusercontent.com/reportportal/jira-versions-sync/main/main.py)"
        env:
          JIRA_SERVER: ${{ env.JIRA_SERVER }}
          JIRA_TOKEN: ${{ secrets.JIRA_TOKEN }}
