name: Actions Runner Controller Demo
on:
  workflow_dispatch:

jobs:
  Explore-GitHub-Actions:
    # You need to use the INSTALLATION_NAME from the previous step
    runs-on: rp-beta-runner-set
    steps:
    - run: echo "🎉 This job uses runner scale set runners!"

  Test-Docker:
    runs-on: rp-beta-runner-set
    steps:      
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

    
